version: "{build}"

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12

branches:
  only:
    - master
    - develop

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_test:
  - node --version
  - npm --version

test_script:
  - npm run lint
  - npm run build
  - npm run build:dev
  - npm run build:prod
  - npm test

build: off

deploy: off
